Controller shorthand and namespaces
zulujive/fiddle pull request #15
Opened 2023-06-29 08:52 UTC by stef1904berg

Controllers are modified to use namespaces

Bramus router allows you to use `Class@method` calls in the router (https://github.com/bramus/router#classmethod-calls), since the controllers are using namespaces it can be used.

2023-07-01 20:40 UTC, zulujive requested changes
The routes file uses "OTP" for POST requests, but the proper function is verifyOTP when handling POST.

2023-07-02 00:28 UTC, stef1904berg commented
Damn, looks like i still missed that one even after a double check.

2023-07-02 01:18 UTC, zulujive commented
All good! Thanks for contributing as well :)

2023-07-02 05:05 UTC, zulujive approved these changes

2023-07-02 05:05 UTC, merged